### ISSUE TITLE
L’interface admin du plugin est inexistante

### ISSUE THREAD

**Issue by Azrty** [MineWeb/Plugin-NewsLetter#1]
Voici:
![e9877038-202e-46a9-a077-aed5135e0ad7](https://user-images.githubusercontent.com/38593367/39219772-97970086-47fa-11e8-85ad-28391e37be3f.jpeg)

**Comment by sadoj-kuro** [comment]
renome le dossier du plugin en Newsletter

@Eywek Faudrait corriger ceci le nom du dossier du plugin doit etre Newsletter et non NewsLetter

j'ai tenter de corriger le route mais c'est de la merde, en corrigeant le route ses le nom du dossier dans /view qui n'est plus bon et qui faut rename alors autant directement rename le dossier sa ira 100x plus vite

**Comment by Eywek** [comment]
Fix
